### ISSUE TITLE
[ User ] LoginUser

### ISSUE THREAD

**Issue by MartinMontanari** [Los-nonos/Gryffindor#32]
------------------------------------------
Tomando como marco de referencia el documento [MVP.](https://docs.google.com/document/d/1IyBGh0oD70od_hAbNn1fLJT8fD1zMvpUlDo5hbCUouE/edit#heading=h.gr5k8mq1evzy)
------------------------------------------
- [x] El ednpoint recibirá:
	- Email.
	- Contraseña.

- [x] Se debe validar que el email esté registrado en la base de datos.
	- En caso de no estar registrado, lanzar excepción y devolver código de error. 
- [x] Si el mail está registrado verificar que el token esté confirmado.
	- Si no está confirmado, lanzar excepción y devolver código de error.
- [x] Si el email está registrado y el token confirmado, conceder acceso al usuario.

**Comment by cristianvena18** [comment]
no se hizo lo que está marcado ya que eso no corresponde con el mvp, el usuario puede acceder y loguearse pero no puede entrar al carro de compras
