### ISSUE TITLE
QueryBuilder & CustomSearchs

### ISSUE THREAD

**Issue by MartinMontanari** [Los-nonos/Gryffindor#48]
- [x] Search by Name

- [x] Search by description

- [ ] Serch by color

- [x] Search by categories

- [x] Search by brand

- [ ] Search by tag

- [ ] Search by price

- [x] Search by price - range

- [x] Search by provider

- [ ] Search by heading (rubro en español)

- [ ] Search by type

**Comment by cristianvena18** [comment]
Agregar por rango de precio y cerrar
